### PR TITLE
Add each_key support to adapters

### PR DESCRIPTION
**Pull request by brutuscat**
Adding support for the following adapters:

* LRUHash
* ActiveRecord
* Redis
* File
* PStore & YAML
* Mongo

Still a WIP. 

I will try to add support for each_key for those adapters where it seems obvious and for those that I might need in the brutuscat/medusa#3 gem (fork of Anemone)

### CODE REVIEW

**Comment by brutuscat** [comment]
@minad @asppsa any pointers on how to implement it for mongodb?

**Comment by asppsa** [comment]
@brutuscat, the thing to be aware of is that there's a bit of magic in `adapters/mongo.rb` to wrap either the `MongoOfficial` or the `MongoMoped` adapter, depending on which one works in the given environment.  So the `each_key` implementation needs to be done for each of those specific adapters, or in the `MongoBase` class, if the API happens to be the same for both adapters.

I'm not super-familiar with Mongo, but I think the relevant docs for iteration are:

* `mongo`: http://api.mongodb.com/ruby/current/Mongo/Cursor.html
* `moped`: http://www.rubydoc.info/gems/moped/2.0.7/Moped/Query

So it looks like `@collection.find.each{ .... }` will do the trick, but then there would be some further improvement possible by limiting the query to just return the `_id`.

**Comment by brutuscat** [comment]
@asppsa I need help with the following specs:

* spec/moneta/cache_file_memory_spec.rb
* spec/moneta/pool_spec.rb

Adding the with_each_key makes things worse... The changes you did on the feature shared cases somehow break everything there.

**Comment by asppsa** [comment]
For `spec/moneta/cache_file_memory_spec.rb` I think it's necessary to add an `each_key` implementation to the Cache class in order to get it to work.  Something like:

~~~~ ruby
    # (see Proxy#each_key)
    def each_key(&block)
      raise NotImplementedError, 'adapter doesn\'t support #each_key' \
        unless supports? :each_key

      return enum_for(:each_key) unless block_given?
      @adapter.each_key(&block)
      self
    end

    # (see Proxy#features)
    def features
      @features ||= ((@cache.features + [:create, :increment, :each_key]) & @adapter.features).freeze
    end
~~~~

Also note addition of `:each_key` to `#features` so that it gets reported if the adapter supports it and the cache doesn't.

For `spec/moneta/pool_spec.rb`, the problem is that the `#each_key` method I wrote for the `Proxy` class calls into `#supports?` (which calls `#features`). This is done so that an `enum_for(...)` doesn't get returned when it's not supported, but it seems to be an issue for some of the wrapper classes, because they haven't been designed to handle proxy methods calling each other (I saw this also with the `Lock` wrapper). 

With `Pool`, it's setting and unsetting `Thread.current[...]` in each call to `wrap`, so if a wrapped method calls another wrapped method, `Thread.current[...]` gets unset too soon.  A simple solution is to implment `#features` separately in `Pool` so that it doesn't rely on `Thread.current[...]`.  e.g.:

~~~ ruby
~~~

Actually, the Pool object probably needs a special implementation of `#each_key` anyway.  The idea of this wrapper is to check out an store object, perform a task on it, and then check it back in.  For `each_key`, we need to think about how we can check out store for an entire enumeration; or if that doesn't make sense,

**Comment by brutuscat** [comment]
@asppsa Moped seems abandoned... I am removing it in this PR, what do u think?

**Comment by asppsa** [comment]
@brutuscat, I agree that moped looks superfluous. In our current testing environment supporting moped is also preventing us from testing against the latest version of the mongo gem as well, so that would be another reason to remove it. 

On the other hand, in current benchmarks , our moped adapter is consistently faster than the mongo one, some times up to 50% faster (e.g. [here][1]), so I don't think we should remove it for now, as we would be forcing poor performance on users.

Hopefully the performance diff is down to something in the adapter code that we can fix or at least improve on.  Anyway, this is a separate issue from `each_key`, so it would be better to handle it in a separate issue/PR.  For this PR, perhaps you can just implement `each_key` in the "official" adapter, in anticipation that moped will be going in the near future?

Thanks for all your work so far!

[1]: https://travis-ci.org/minad/moneta/jobs/359320014

**Comment by asppsa** [comment]
@brutuscat, I think I've solved the issues with the `Pool` wrapper in 1e609987715d4a63b156143b0ced9164b46676a8 by making the wrapper "reentrant".

**Comment by brutuscat** [comment]
@asppsa I finally ([almost](https://travis-ci.org/minad/moneta/builds/394693929?utm_source=github_status&utm_medium=notification)) fixed the specs and I implemented each_keyin both Mongo adapters.

I have 2 set of problems now that I think you can help me :)

- Some specs are failing and I have no clue why. See https://travis-ci.org/minad/moneta/jobs/394693960. (uninitialized constant Moneta::Expires::Utils)
- For mongo (and I think other adapters too), when I instrument the with_each_key specs for the STANDARD_SPECS collection, is as if the Proxy is not picking up the [addition of :each_key in the `supports` collection](https://github.com/minad/moneta/pull/136/commits/8d0a820d6fef2113dc53100019dfc97644da32ba#diff-50b20ca84f972b8d4010e27a9124a49eR10). Therefore I get NotImplementedError: each_key is not supported on this proxy.

**Comment by asppsa** [comment]
Hiya,

- The first issue (uninitialized constant) is an oldie -- something to do with multithreading and autoloading -- it's only sporadic in the specs and doesn't seem to have an easy fix, so I think it's probably not worth worrying about (see #141 if you want to try to fix this though).
- The second one is because the standard adapters (using `Moneta.new(...)`) often apply key transformations (e.g. marshal), and we have explicitly disabled `each_key` support in that case for the time being.  So you don't need to worry about adding `with_each_key` to most of the `standard_*_spec.rb` files (definitely not for standard mongo).

Looking good though!

**Comment by brutuscat** [comment]
@asppsa specs fixed, but rspec ./spec/moneta/standard_hashfile_with_expires_spec.rb is giving me some trouble.

**Comment by asppsa** [comment]
The various `_with_expires` specs fail intermittently at the moment, so that's not your fault.  So are we ready to merge this?

**Comment by brutuscat** [comment]
👍 🍺

**Comment by asppsa** [comment]
@brutuscat, thank you for all your work on this!

**Comment by bjeanes** [comment]
Does README need to be updated? I haven't checked others, but ActiveRecord's entry states that is does not support key traversal.

**Comment by asppsa** [comment]
Yes, you are right. We haven't done a release with the key traversal feature yet. I've added this to #154

**Pull request merged**
